feature/mesa-class
P2023-ESI1005A/sd_restaurant_app pull request #2
Opened 2023-02-16 18:11 UTC by pagabo18

Implemented the classes of: Mesa, Empleados, Mesero, Cocineros, Gerente

2023-02-16 20:12 UTC, gustavoSo3 commented on mesa/mesa.py
> +class Mesero(ABC):
No deberia de ser la interfaz Empleados? y Mesero, Gerente y Cocinero usarla

2023-02-16 20:15 UTC, pagabo18 commented on mesa/mesa.py
> +class Mesero(ABC):
Cambiaron muchas cosas en la clase, nos pidieron que hicieramos la clase mesa

2023-02-16 20:16 UTC, pagabo18 commented on mesa/mesa.py
> +class Mesero(ABC):
Cambiaron muchas cosas en la clase, nos pidieron que hicieramos la clase mesa

2023-02-18 03:22 UTC, gustavoSo3 commented on mesa/mesa.py
> +class Mesero(ABC):
Arre va, andaba basandome en el diagrama, pero perfecto.

2023-02-18 16:59 UTC, BamCurti requested changes

2023-02-18 16:59 UTC, BamCurti commented on mesa/mesa.py
> +#         self.empleado_asignado:Mesero = mesero.nombre
No se debe de dejar código comentado.  Elimínalo del código.

2023-02-18 16:59 UTC, BamCurti commented on mesa/mesa.py
> +
Por favor, sigue las normas de PEP8 y deja dos saltos de línea entre clases y funciones en la primera identación.

2023-02-18 16:59 UTC, BamCurti commented on mesa/mesa.py
> +class Empleados:
No entiendo porqué esta clase está en este archivo. Por favor, crea un directorio con su respectivo archivo __init__.py para formalizarlo como módulo, y que sean importados cuando sea necesario.

Punto y Aparte, los nombre de las clases deben de ser en singular, no puede haber una clase Empleados, sino Empleado.

2023-02-18 16:59 UTC, BamCurti commented on mesa/mesa.py
> +#print(com1.agregar_productos()," Se realizo algo ")
Según PEP8, solo debe de haber una linea vacía al final del archivo. Elimina los espacios extras y elimina el código comentado.

2023-02-18 21:09 UTC, merged